name: Pack executable

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install compiler (required for Nuitka)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          pip install flask

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: monitool.py
          mode: standalone
          include-data-files: templates/*.html=templates/

      # Correct output path for onefile
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/monitool.dist/monitool.bin

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/monitool.dist/monitool.bin
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
